// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAym1WehuHmcSlqBWFce28bvwA3i8NvWvM',
    appId: '1:698910135784:web:b00f115e7c001e91e4c05d',
    messagingSenderId: '698910135784',
    projectId: 'fir-01-976ba',
    authDomain: 'fir-01-976ba.firebaseapp.com',
    storageBucket: 'fir-01-976ba.appspot.com',
    measurementId: 'G-Y6V40XCPNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSQH8aYXVqb6USGIkIJD4G-2tN8erPem4',
    appId: '1:698910135784:android:f307f08aa38b9e00e4c05d',
    messagingSenderId: '698910135784',
    projectId: 'fir-01-976ba',
    storageBucket: 'fir-01-976ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo7GxSNHdHHoTsp2Lj6mErduqH8jc3ci4',
    appId: '1:698910135784:ios:6e54b208f759c509e4c05d',
    messagingSenderId: '698910135784',
    projectId: 'fir-01-976ba',
    storageBucket: 'fir-01-976ba.appspot.com',
    iosBundleId: 'com.example.coffeeShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo7GxSNHdHHoTsp2Lj6mErduqH8jc3ci4',
    appId: '1:698910135784:ios:6e54b208f759c509e4c05d',
    messagingSenderId: '698910135784',
    projectId: 'fir-01-976ba',
    storageBucket: 'fir-01-976ba.appspot.com',
    iosBundleId: 'com.example.coffeeShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAym1WehuHmcSlqBWFce28bvwA3i8NvWvM',
    appId: '1:698910135784:web:0db156ea5864bb81e4c05d',
    messagingSenderId: '698910135784',
    projectId: 'fir-01-976ba',
    authDomain: 'fir-01-976ba.firebaseapp.com',
    storageBucket: 'fir-01-976ba.appspot.com',
    measurementId: 'G-WFGR9RZHZ3',
  );
}
